export const data = [
  {
    id: 1,
    title: "Puss in Boots: The Last Wish",
    body: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    rate: 8.611,
    tags: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
    date: 2022,
    img: "./img/2022.jpg",
  },
  {
    id: 2,
    title: "Avatar",
    body: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    rate: 7.564,
    tags: ["Action", "Adventure", "Fantasy", "Sci - Fi"],
    date: 2009,
    img: "./img/2009.jpg",
  },
  {
    id: 3,
    title: "The Shawshank Redemption",
    body: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    rate: 3,
    tags: ["Drama"],
    date: 1994,
    img: "./img/1994.jpg",
  },
  {
    id: 4,
    title: "The Godfather",
    body: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    rate: 8.714,
    tags: ["Crime", "Drama"],
    date: 1972,
    img: "./img/1972.jpg",
  },
  {
    id: 5,
    title: "Er Ryan'ı Kurtarmak",
    body: "II. Dünya Savaşı yıllarında 3 oğlunun birden ölüm haberini alan anne, 4. oğlunun yaşadığını duymak ister.Artık tüm Amerikan ordusunun hedefi annenin son oğlu olan James Ryan'ı ne pahasına olursa olsun kurtarmaktır. Askerler her yerde ona ait izler aramaya başlar fakat bu öylesine bir göreve dönüşür ki bir kişiyi kurtarmak uğruna bir çok askerin hayatı tehlikeye girer.",
    rate: 8.8,
    tags: ["Tarih", "Drama", "Savaş"],
    date: 1998,
    img: "./img/1998.jpg",
  },
  {
    id: 6,
    title: "Cesur Yürek",
    body: "13. yüzyılda İngilizler, İskoçlar üzerinde egemenlik kurmuştur. İngiliz soyluları, yeni evli İskoç kadınlarıyla ilk geceyi geçirme hakkına sahiptir. Çocukken ailesini İskoçya uğruna kaybeden William Wallace'ın karısı da İngiliz birlikleri tarafından öldürüldüğü zaman, onun intikam arayışı kısa zamanda ülkesinin özgürlüğü için amansız bir savaşa dönüşür.",
    rate: 8.7,
    tags: ["aksiyon", "Drama", "Tarih", "Savaş"],
    date: 1995,
    img: "./img/1995.jpg",
  },
  {
    id: 7,
    title: "Truva",
    body: "On yıl süren ve bir medeniyetin çöküşüne neden olacak savaşı, Truva prensi Paris ile Isparta Kraliçesi Helen'in aşkı başlatır. Paris’in Helen’i kocası Kral Menelaus’tan çalması kabul edilemeyecek bir hakarettir. Aile onuru Menelaus’a yapılan bu yanlış hareketin kardeşi Agamemnon’a da yapıldığını öngörmektedir. Mikene Kralı olarak büyük bir güce sahip olan Agamemnon, Helen’i Truva’dan geri getirerek kardeşinin şerefini kurtarmak için kısa sürede Yunanistan’ın tüm ordularını bir araya toplar.",
    rate: 8.2,
    tags: ["Macera", "tarih", "savaş", "aksiyon"],
    date: 2004,
    img: "./img/2004.jpg",
  },
  {
    id: 8,
    title: "Cennetin Krallığı",
    body: "Ailesini ve inancını kaybeden acılı bir baba... Dini savaş uzak ve kutsal topraklarda devam etmekte onu ve kaderini ise büyük bir drama doğru yönlendirmektedir. Kaderi oğlu Balian’ın büyük bir şövalye olmasını sağlayacaktır. Ibelin’li Godfrey Doğu’da savaştığı Haçlı Seferlerinden vatanı Fransa’ya dönmüştür. Balian’ın babası olduğu ortaya çıkınca, Godfrey gerçek şövalyeliğin ne olduğu hakkında oğlunu yetiştirecek ve onu kıtalararası destansı bir yolculuğa çıkaracaktır. Kudüs’te o günlerde 2. ve 3. Haçlı Seferleri arasında kırılgan ve her an sonlanabilecek bir ateşkes ilan edilmiştir.",
    rate: 8.4,
    tags: ["Tarih", "Drama", "Savaş"],
    date: 2005,
    img: "./img/2005.jpg",
  },
];
